### ISSUE TITLE
license on version level description

### ISSUE THREAD

**Issue by micheldumontier** [indiedotkim/HCLSDatasetDescriptions#110]
Currently we have the license at a version level description as a "MUST", but i think we should relax this to MAY, and keep the MUST for the distribution level description.

**Comment by AlasdairGray** [comment]
It is clear that the license is a MUST for the distribution, as without it the data cannot be reused.
The argument for having it as a MAY at the summary level is that different versions can be shipped with different licenses.
What is the reason for reducing the requirement on the version level and why MAY rather than SHOULD?

**Comment by micheldumontier** [comment]
SIDER actually have file specific licensing http://sideeffects.embl.de/download/

**Comment by micheldumontier** [comment]
reasons for making it a recommendation:
1. uniform licensing across all data files
2. make it easier to track version changes
